name: Continuous Delivery
on:
  push:
    branches:
      - 'master'
      - 'feature/autoRelease'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking build
        uses: actions/checkout@v2
      - run: bash replace.sh
      
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
      - run: ls dist/windows
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Building deployment artifact
        uses: actions/checkout@v2
      - run: bash replace.sh

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - uses: actions/upload-artifact@v2
        with:
          name: windows-chess
          path: dist/windows
      
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: .    
      - uses: actions/upload-artifact@v2
        with:
          name: linux-chess
          path: dist/linux
      
      - name: Create GitHub release
        id: create_new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.${{ github.run_number }}
          release_name: 1.0.${{ github.run_number }}
      - name: see folder content
        run: ls -R dist/

      - name: Upload Windows installer to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_new_release.outputs.upload_url }}
          asset_path: ./dist/windows/chess.exe
          asset_name: windows-chess.exe
          asset_content_type: application/octet-stream
      - name: Upload Linux installer to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_new_release.outputs.upload_url }}
          asset_path: ./dist/linux/chess
          asset_name: linux-chess
          asset_content_type: application/octet-stream

